"""
config.py

Project-wide configuration for LocateAnything-3B.
Keeping all configurable parameters in one place makes the
project easier to maintain and extend.
"""

# ==========================================================
# Model Configuration
# ==========================================================

MODEL_NAME = "nvidia/LocateAnything-3B"

# ==========================================================
# Generation Configuration
# ==========================================================

GENERATION_CONFIG = {
    # Maximum number of tokens generated by the model
    "max_new_tokens": 10,

    # Sampling parameters
    "temperature": 0.7,
    "top_p": 0.9,
    "do_sample": True,

    # Reduce repetitive outputs
    "repetition_penalty": 1.1,

    # Faster inference
    "use_cache": True,

    # Print model generation statistics
    "verbose": True,
}

# ==========================================================
# Project Directories
# ==========================================================

IMAGE_FOLDER = "images"

OUTPUT_FOLDER = "outputs"

NOTEBOOK_FOLDER = "notebooks"

ASSETS_FOLDER = "assets"

# ==========================================================
# Evaluation Configuration
# ==========================================================

EVALUATION_CONFIG = {
    # Number of COCO validation images used during evaluation
    "num_images": 10,

    # Output files
    "csv_output": "results/evaluation.csv",
    "summary_output": "results/summary.json",
}